### ISSUE TITLE
Verbose "debugging" info

### ISSUE THREAD

**Issue by xidulu** [justindomke/pangolin#6]
I believe the print statement at

https://github.com/justindomke/pangolin/blob/main/pangolin/interface.py#L307

https://github.com/justindomke/pangolin/blob/main/pangolin/interface.py#L295

https://github.com/justindomke/pangolin/blob/main/pangolin/inference_numpyro.py#L105

Could be commented out or be activated under, e.g. "DEBUG" flag? These statements are really printing out LOTS of stuff.

**Comment by justindomke** [comment]
Agreed, there were way too many random print statements. I seem to have coincidentally removed all these comments before seeing this issue, but please let me know if there are any others. Broadly speaking, Pangolin should in general "shut up and give the answer" since we want it to be usable for simple one-liners like `var(binomial(5,.2))`
